Updates to stop, start, and create supervisor config

diff --git a/usr/versions/2.7/bin/control b/usr/versions/2.7/bin/control
--- a/usr/versions/2.7/bin/control
+++ b/usr/versions/2.7/bin/control
@@ -6,7 +6,7 @@ source "${OPENSHIFT_PYTHON_DIR}/usr/versions/${OPENSHIFT_PYTHON_VERSION}/lib/wis
 
 
 SUPERVISORD="${VE_ROOT}/bin/supervisord -c ${OPENSHIFT_PYTHON_DIR}etc/supervisord.conf"
-SUPERVISORCTL="${VE_ROOT}/bin/supervisorctl"
+SUPERVISORCTL="${VE_ROOT}/bin/supervisorctl  -c ${OPENSHIFT_PYTHON_DIR}etc/supervisord.conf"
 
 # For backwards compatibility
 export APPDIR=$OPENSHIFT_PYTHON_DIR
@@ -14,7 +14,7 @@ export APPDIR=$OPENSHIFT_PYTHON_DIR
 function start() {
 
     if is_running; then
-      echo "Application is already running!" 1>&2
+      echo "The patton-based application appears to be running already." 1>&2
       return 0
     fi
 
@@ -22,48 +22,59 @@ function start() {
     . env.sh
     create_supervisor_config
     mkdir -p $OPENSHIFT_PATTON_RUN_DIR
+
+    # Make sure supervisor is dead
+    $SUPERVISORCTL shutdown
+
+    # Then start it up
     $SUPERVISORD
 }
 
 
 function stop() {
-    echo "Stopping PYTHON cart"
 
     if ! is_running; then
-      echo "Application is already stopped!" 1>&2
+      echo "The patton-based application appears to be stopped already." 1>&2
       return 0
     fi
 
    pushd $OPENSHIFT_REPO_DIR > /dev/null
-     . env.sh
+     echo "Shutting down the supervisor."
      $SUPERVISORCTL shutdown
 }
 
 
 function restart() {
-    echo "Reloading supervisord"
 
-    # Update the supervsior configuration
-    create_supervisor_config
-    $SUPERVISORCTL reload
+    if ! is_running; then
+      echo "Cannot restart; the supervisor is not running." 1>&2
+      return 0
+    fi
+
+    echo "Reloading supervisord."
+
+    # Update the supervsior configuration before reloading
+    pushd $OPENSHIFT_REPO_DIR > /dev/null
+      create_supervisor_config
+      $SUPERVISORCTL reload
 }
 
 function status() {
     if is_running; then
-        client_result "Application is running"
+        client_result "Application is running."
     else
-        client_result "Application is either stopped or inaccessible"
+        client_result "Application is either stopped or inaccessible."
     fi
 }
 
 function reload() {
-    echo "Reloading PYTHON cart"
+    echo "Reloading the application."
     restart
 }
 
 # Clean up any log files
 function tidy() {
-  client_message "Emptying log dir: $OPENSHIFT_PATTON_LOG_DIR"
+  client_message "Emptying log dir: $OPENSHIFT_PATTON_LOG_DIR."
   shopt -s dotglob
   rm -rf $OPENSHIFT_PATTON_LOG_DIR/*
 }
@@ -78,12 +89,12 @@ function build() {
     fi
 
     if force_clean_build_enabled_for_latest_deployment; then
-        echo "Force-clean builds are enabled" 1>&2
+        echo "Force-clean builds are enabled." 1>&2
         remove-virtenv
     fi
 
     if [ ! -f $VIRTUAL_ENV/bin/python ]; then
-      echo "Recreating virtenv" 1>&2
+      echo "Recreating virtenv." 1>&2
       create-virtenv
     fi
 
